
language: java

before_install:
  - chmod +x mvnw

cache:
  directories:
    - $HOME/.m2

addons:
  sonarcloud:
    organization: "mls-cs"
    token:
      secure: $SONAR_TOKEN

services:
  - docker

script:
  - ./mvnw clean jacoco:prepare-agent install -Pci -Dsonar.projectKey=MLS-CS_survey-submission-service  -Dsonar.host.url=https://sonarcloud.io
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push anantpawar/survey-submission-service